language: cpp
compiler: gcc
sudo: required
install:
    - echo | sudo apt-add-repository ppa:boost-latest/ppa
    - sudo apt-get update
    - sudo apt-get install libboost-dev libsnappy-dev zlib1g-dev
script: 
    - sh -x ubuntu_build.sh

env:
  global:
    - secure: "fk8ZMcLDYG+fTkSzLrNDWbMjqk+XojEaTZ4ozHg2oEH5P8zylRvPHaK9SU1fzZ3im6aPoiIJa8HYB/gE3niWOwhfZgw09OZZKJ+f1JfUyzH0OhJ7tGidy90kQ3c589nxadiGSGmtoEmy52sxYCg2G7Hf4gUkF1/Rkv++JM/GF5Y="
  matrix:
    - PATH=$PATH:./depends/bin

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "baidu/ins"
      description: "iNexus, coordinate large scale services"
    notification_email: j.zhangkai1994@gmail.com
    build_command_prepend: "sh ./ubuntu_build.sh; make clean"
    build_command:   "make -j 4"
    branch_pattern: master
